FROM node:alpine3.20

WORKDIR /tmp

# 先复制 package-de.json 并改名为 package.json，保证 npm install 用 DE 版依赖
COPY package-de.json package.json

# 再复制其他所有代码文件
COPY . .

EXPOSE 3000/tcp

RUN apk update && apk upgrade &&\
    apk add --no-cache openssl curl gcompat iproute2 coreutils &&\
    apk add --no-cache bash &&\
    chmod +x index-de.js &&\
    npm install

CMD ["node", "index-de.js"]
